name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
     - 'main'
    paths:
    - 'src/model/*'
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'aibx-ml-rg'
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'aibx-ml-mlw-dev-rg'
        type: string
env:
  rg: '****'
  amlw: '****'

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Define rg and amlw
        run: |
          echo "rg=$rg"
          echo "amlw=$amlw"
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            rg="${{ github.event.inputs.resource_group }}"
            amlw="${{ github.event.inputs.aml_workspace }}"
            echo "rg=${{ env.rg }}" >> "$GITHUB_ENV"
            echo "amlw=${{ env.amlw }}" >> "$GITHUB_ENV"
          fi
